[package]
authors = ["Volker Kempert <volker.kempert@almedso.de>"]
name = "manchester-code"
publish = false
edition = "2018"
version = "0.1.0"

[dependencies]
defmt = "0.3.0"
embedded-hal = { version = "0.2.5", features = ["unproven"] }
